service_ip: 192.168.241.128
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://${service_ip}:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ch0805-seata-account-provider

mybatis:
  mapper-locations: classpath*:wjc/scab/ch0805/seata/account/provider/dal/mappers/*Mapper.xml
  type-aliases-package: wjc.scab.ch0805.seata.account.provider.dal.entitys

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://${service_ip}:8848
  protocol:
    name: dubbo
    port: 20882
  scan:
    base-packages: wjc.scab.ch0805.seata.account.provider.impl

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  transport:
    type: TCP
    server: NIO
    heartbeat: true
    enable-client-batch-send-request: true
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      boss-thread-size: 1
      worker-thread-size: 8
    shutdown:
      wait: 3
    serialization: seata
    compressor: none
  service:
    vgroupMapping:
      default: ${spring.application.name}
    enable-degrade: false
    disable-global-transaction: false
    #grouplist: 192.168.216.128:8091
  config:
    type: nacos
    nacos:
      #需要和server在同一个注册中心下
      serverAddr: ${service_ip}:8848
      #需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
      namespace: e1250570-24fc-47c9-973d-fda5b0a09077
  registry:
    type: nacos
    nacos:
      #需要和server端保持一致，即server在nacos中的名称，默认为seata-server
      application: seata-server
      serverAddr: ${service_ip}:8848
      #需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
      namespace: e1250570-24fc-47c9-973d-fda5b0a09077
  client:
    rm:
      lock:
        lock-retry-interval: 10
        lock-retry-policy-branch-rollback-on-conflict: true
        lock-retry-times: 30
    rm-async-commit-buffer-limit: 10000
    rm-report-retry-count: 5
    rm-table-meta-check-enable: false
    rm-report-success-enable: true
    tm-commit-retry-count: 5
    tm-rollback-retry-count: 5
    undo:
      undo-log-table: undo_log
      undo-data-validation: true
      undo-log-serialization: jackson
    log:
      exception-rate: 100
    support:
      spring:
        datasource-autoproxy: true

nacos:
  discovery:
    server-addr: ${service_ip}:8848

